# Generated by Django 2.2.1 on 2019-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=6)),
                ('password2', models.CharField(max_length=6)),
            ],
        ),
    ]
