# Generated by Django 2.2.1 on 2019-12-05 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregmodel',
            name='mailsent',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
